openapi: 3.0.0
info:
  title: IndeJuice Logistics Vendor API
  version: 1.0.0
  description: >
    API documentation for the Vendor Product Catalogue system.
    This API allows vendors to upload and update product batches
    with a maximum payload size of 2 MB.
servers:
  - url: http://localhost:3000/api/v1
    description: Local development server

paths:
  /vendor/upload-products:
    $ref: './openapi/paths/vendor/product/upload-products.yml#/post'
  /vendor/update-products:
    $ref: './openapi/paths/vendor/product/update-products.yml#/put'
  # Add additional paths as needed, e.g. stockshipment, order

components:
  securitySchemes:
    $ref: './openapi/components/securitySchemes.yml'
  schemas:
    product:
      $ref: './openapi/components/schemas/product.yml'
    product_update:
      $ref: './openapi/components/schemas/product-update.yml'
    # Add more schemas as needed