openapi: 3.0.0
info:
  title: Vendor Product Catalogue API
  version: 1.0.0
  description: >
    API documentation for the Vendor Product Catalogue system.
    This API allows vendors to upload and update product batches
    with a maximum payload size of 2 MB.
servers:
  - url: http://localhost:3000/api/v1
    description: Local development server

paths:
  /vendor/upload-products:
    post:
      summary: Upload product catalog
      description: >
        Endpoint for vendors to upload their product catalog in batches.
        The payload must contain a maximum of 500 products and should not exceed 5 MB in size.
        Requires API token for authentication.
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                products:
                  type: array
                  maxItems: 5000
                  items:
                    $ref: '#/components/schemas/product'
      responses:
        '200':
          description: Products uploaded successfully
        '400':
          description: Validation errors or request payload exceeds limits
        '401':
          description: Unauthorized - Missing or invalid API token
        '413':
          description: Payload exceeds the allowed size limit (5 MB)
        '500':
          description: Server error

  /vendor/update-products:
    put:
      summary: Update existing products
      description: >
        Endpoint for vendors to update existing products in batches. The payload size must not exceed 2 MB. The `vendor_sku` is required, and any other attribute can be optionally updated. The request must contain at least one field to update in addition to `vendor_sku`.
        Requires API token for authentication.
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                products:
                  type: array
                  maxItems: 5000
                  items:
                    $ref: '#/components/schemas/product_update'
      responses:
        '200':
          description: Products updated successfully
        '400':
          description: Validation errors or request payload exceeds limits
        '401':
          description: Unauthorized - Missing or invalid API token
        '413':
          description: Payload exceeds the allowed size limit (2 MB)
        '500':
          description: Server error

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    product:
      type: object
      required:
        - vendor_sku
        - status
        - stock
        - name
        - cost_price
        - sale_price
        - brand_name
        - image
      properties:
        vendor_sku:
          type: string
          example: "12345678"
        status:
          type: string
          example: "Active"
        stock:
          type: integer
          example: 50
        name:
          type: string
          example: "Example Product"
        cost_price:
          type: number
          example: 90.41
        sale_price:
          type: number
          example: 126.98
        brand_name:
          type: string
          example: "Brand 1"
        image:
          type: string
          example: "https://cdn.indejuice.com/image1.jpg"
        attributes:
          type: object
          additionalProperties:
            type: string
          example:
            color: "Red"
            size: "Medium"
            nicotine: ["0mg", "3mg"]

    product_update:
      type: object
      required:
        - vendor_sku
      properties:
        vendor_sku:
          type: string
          example: "12345678"
        new_vendor_sku:
          type: string
          example: "987654321"
        status:
          type: string
          enum: [Active, Inactive]
          example: "Active"
        stock:
          type: integer
          example: 100
        name:
          type: string
          example: "Updated Product Name"
        cost_price:
          type: number
          example: 80.99
        sale_price:
          type: number
          example: 120.50
        brand_name:
          type: string
          example: "Updated Brand"
        image:
          type: string
          example: "https://cdn.indejuice.com/updated_image.jpg"
        attributes:
          type: object
          additionalProperties:
            type: string
          example:
            color: "Blue"
            size: "Large"
            nicotine: ["6mg", "12mg"]
    