type: object
required:
  - vendor_sku
  - status
  - stock
  - name
  - cost_price
  - sale_price
  - brand_name
  - image
properties:
  vendor_sku:
    type: string
    example: "12345678"
  status:
    type: string
    enum:
      - Active
      - Inactive
    example: "Active"
  stock:
    type: integer
    example: 50
  name:
    type: string
    example: "Example Product"
  cost_price:
    type: number
    example: 90.41
  sale_price:
    type: number
    example: 126.98
  brand_name:
    type: string
    example: "Brand 1"
  image:
    type: string
    example: "https://cdn.example.com/image1.jpg"
  attributes:
    type: object
    additionalProperties:
      type: string
    example:
      color: "Red"
      size: "Medium"
      nicotine:
        - "0mg"
        - "3mg"
