product:
  type: object
  required:
    - vendor_sku
    - status
    - name
    - cost_price
    - sale_price
    - brand_name
    - image
  properties:
    vendor_sku:
      type: string
      example: "12345678"
    status:
      type: string
      example: "Active"
    name:
      type: string
      example: "Example Product"
    cost_price:
      type: number
      example: 90.41
    sale_price:
      type: number
      example: 126.98
    brand_name:
      type: string
      example: "Brand 1"
    image:
      type: string
      example: "https://cdn.indejuice.com/image1.jpg"
    attributes:
      type: object
      additionalProperties:
        type: string
      example:
        color: "Red"
        size: "Medium"
        nicotine: ["0mg", "3mg"]