product_update:
  type: object
  required:
    - vendor_sku
  properties:
    vendor_sku:
      type: string
      example: "12345678"
    new_vendor_sku:
      type: string
      example: "987654321"
    status:
      type: string
      enum: [active, inactive]
      example: "active"
    stock_available:
      type: integer
      example: 100
    name:
      type: string
      example: "updated product name"
    cost_price:
      type: number
      example: 80.99
    sale_price:
      type: number
      example: 120.50
    brand_name:
      type: string
      example: "updated brand"
    image:
      type: string
      example: "https://cdn.indejuice.com/updated_image.jpg"
    attributes:
      type: object
      additionalProperties:
        type: string
      example:
        color: "Blue"
        size: "Large"
        nicotine: "6mg"